### ISSUE TITLE
"X-Gu-Membership-Test-User" header always false because using identityID rather than firstName

### ISSUE THREAD

**Issue by twrichards** [guardian/members-data-api#335]
https://github.com/guardian/members-data-api/blob/a5f602b3046bbc2aee2ac49e029fe4bfe7606156/membership-attribute-service/app/filters/AddGuIdentityHeaders.scala#L28

**Comment by twrichards** [comment]
@rtyley @johnduffell @jacobwinch @pvighi any ideas about what things use this value? NOTE: this is the response headers for members-data-api, the actual [WithBackendFromCookieAction](https://github.com/guardian/members-data-api/blob/a5f602b3046bbc2aee2ac49e029fe4bfe7606156/membership-attribute-service/app/actions/WithBackendFromCookieAction.scala) does it correctly so members-data-api does actually connect to the desired backend - perhaps hence why it hasn't been noticed

**Comment by johnduffell** [comment]
I think that is just for logging, we used to (maybe still do) log it at fastly. But it has to be a header to be loggable there.

**Comment by twrichards** [comment]
in which case its logging incorrect values, i.e. fastly logs won't think there are any test-users coming through. Shall I do a fix?
