### ISSUE TITLE
top level expiry dates on the /me response should only be present for non-auto-renewing or cancelled subs

### ISSUE THREAD

**Issue by twrichards** [guardian/members-data-api#364]
![image](https://user-images.githubusercontent.com/19289579/51610695-468e0e80-1f15-11e9-9dfa-9526b0d21990.png)
... should really only show if the subscriptions they represent are NOT auto-renew or cancelled (otherwise expiry is effectively infinite).

The `digitalSubscriptionExpiryDate` at least is used in the Daily Edition at least as so @jorgeazevedo is confirming if it not always being present will break anything.

**Comment by jorgeazevedo** [comment]
The github code search results we saw were quite misleading I'm afraid!

The expiry date property is actually a core part of how the daily edition computes whether to give access to a user or not. For example, the fact that there's always an expiry date present is an assumption the code builds upon. @SLambrakis reviewed the code, she'd be happy to talk about it if you'd like to know more details

**Comment by twrichards** [comment]
@paulbrown1982 looks like Daily Edition is relying heavily on...
https://github.com/guardian/members-data-api/blob/a8f28b604248a7097853b8097381edd2b71b7bdd/membership-attribute-service/app/services/AttributesMaker.scala#L113
... for determining editions the user can see (expiry in the next 7 days), I fear that because the above line is just picking the largest of the `termEndDate` this could be causing problems as users near their renewal date. Any thoughts?

**Comment by twrichards** [comment]
As per discussion with @jorgeazevedo and @SLambrakis this isn't causing the feared problems and changing to an arbitrary date in the future if the sub is active and auto-renewing could be problematic... so closing this issue as no action required.
